Name = "Arcrylic"
Version = "1.0.0"
Description = "A module to apply acrylic blur effect to Windows application windows"
Author = "Wnclient Dev Team"
Dependence = ["ctypes","pywin32"]
platforms = ["Windows"]
Run_in_the_background = false